---
# Installs nginx and makes sure we can redirect *.dev to custom ports

- name: Install nginx
  homebrew: name=nginx state=present

- name: Load nginx at startup
  file: src=/usr/local/opt/nginx/homebrew.mxcl.nginx.plist dest=/Library/LaunchDaemons/homebrew.mxcl.nginx.plist state=link
  sudo: yes

- name: Make sure it can run as root
  file: path=/usr/local/opt/nginx/homebrew.mxcl.nginx.plist owner=root group=wheel
  sudo: yes

- name: Create sites directory
  file: path=/usr/local/etc/nginx/sites state=directory

- name: Start nginx
  command: launchctl load /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
  sudo: yes

- name: Load all vhosts
  lineinfile: "dest=/usr/local/etc/nginx/nginx.conf insertafter='http {' line='    include /usr/local/etc/nginx/sites/*.conf; # nginx-app; Load all vhosts'"

- name: Install dnsmasq
  homebrew: name=dnsmasq state=present

- name: Setup dnsmasq conf for *.dev
  lineinfile: dest=/usr/local/etc/dnsmasq.conf line='address=/.dev/127.0.0.1' state=present create=yes

- name: Setup dnsmqas autolaunch
  copy: src=/usr/local/opt/dnsmasq/homebrew.mxcl.dnsmasq.plist dest=/Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist owner=root group=wheel
  sudo: yes

- name: Launch dnsmasq
  command: launchctl load /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
  sudo: yes

- name: Setup resolver directory
  file: path=/etc/resolver state=directory
  sudo: yes

- name: Redirect all *.dev requests to dnsmasq
  lineinfile: dest=/etc/resolver/dev line='nameserver 127.0.0.1' create=yes state=present
  sudo: yes