---
# Everything related to ruby
- name: Install chruby
  homebrew: name=chruby state=present
- name: Install ruby-install
  homebrew: name=ruby-install state=present
- include: ruby-install.yml rubies={{ rubies }}
  vars:
    rubies:
      - {flavor: "ruby", version: "2.0"}
      - {flavor: "ruby", version: "2.1"}
      - {flavor: "ruby", version: "2.2"}
      - {flavor: "ruby", version: "1.9"}
- name: Check for phantomjs
  stat: path=/usr/local/bin/phantomjs
  register: phantom_installed
- include: phantomjs.yml phantomjs_url="https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-macosx.zip"
  when: phantom_installed.stat.exists == false
